CREATE TABLE USERS(
    ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    USERNAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    ROLE ENUM('ADMIN','SELLER','SUPPORTER','CUSTOMER'),
    PRIMARY KEY(ID)    
);

